FERNVERKEHR_BHFS = [
    "Aachen Hbf",
    "Aalen Ainring",
    "Alfeld (Leine)",
    "Altenbeken",
    "Andernach",
    "Angermünde",
    "Anklam",
    "Ansbach",
    "Apolda",
    "Aschaffenburg Hbf",
    "Augsburg Hbf",
    "Augustfehn",
    "Aulendorf",
    "Bad Bentheim",
    "Bad Bevensen",
    "Baden-Baden",
    "Bad Endorf (Oberbayern)",
    "Bad Hersfeld",
    "Bad Kleinen",
    "Bad Nauheim",
    "Bad Oeynhausen",
    "Bad Reichenhall",
    "Bad Reichenh-Kir",
    "Bad Schandau",
    "Bad Zwischenahn",
    "Bamberg",
    "Bansin Seebad",
    "Basel Badischer Bf",
    "Bayerisch Gmain",
    "Bebra",
    "Bensheim",
    "Berchtesgarden Hbf",
    "Bergen auf Rügen",
    "Berlin Gesundbrunnen",
    "Berlin Hbf",
    "Berlin Ostbahnhof",
    "Berlin Schönefeld Flh",
    "Berlin Spandau",
    "Berlin Südkreuz",
    "Berlin Wannsee",
    "Bernau (bei Berlin)",
    "Biberach (Riß)",
    "Bielefeld Hbf",
    "Bingen (Rhein) Hbf",
    "Bischofswiesen",
    "Bitterfeld",
    "Bochum Hbf",
    "Bonn Hbf",
    "Boppard Hbf",
    "Brandenburg Hbf",
    "Braunschweig Hbf",
    "Bremen Hbf Bruchsal",
    "Büchen",
    "Buchloe",
    "Bullay DB",
    "Bünde (Westfalen)",
    "Bützow",
    "Calau (Niederlande)",
    "Celle",
    "Cochem (Mosel)",
    "Cottbus",
    "Crailsheim",
    "Darmstadt Hbf",
    "Delmenhorst",
    "Diepholz",
    "Donaueschingen",
    "Donauwörth",
    "Dortmund Hbf",
    "Dresden Hbf",
    "Dresden Neustadt",
    "Duisburg Hbf",
    "Düren Pbf",
    "Düsseldorf Flughafen",
    "Düsseldorf Hbf",
    "Eberswalde Hbf",
    "Eisenach",
    "Ellwangen",
    "Elmshorn",
    "Elsterwerda",
    "Elze (bei Hannover)",
    "Emden",
    "Emden Außenhafen",
    "Erfurt Hbf",
    "Erlangen",
    "Essen Hbf",
    "Feldkirch",
    "Fischen",
    "Flensburg",
    "Forst (Lausitz)",
    "Foto: Max Mustermann",
    "Frankfurt (Main) Flughafen",
    "Frankfurt (Main) Hbf",
    "Frankfurt (Main) Süd",
    "Frankfurt (Main) West",
    "Frankfurt (Oder)",
    "Freiburg (Breisgau) Hbf",
    "Freilassing",
    "Friedberg (Hessen)",
    "Friedrichshafen Stadt",
    "Fulda",
    "Garmisch-Partenkirchen",
    "Geislingen (Steige)",
    "Gelsenkirchen Hbf",
    "Gemünden (Main)",
    "Gießen",
    "Göppingen",
    "Gotha",
    "Göttingen",
    "Greifswald",
    "Günzburg",
    "Gunzenhausen",
    "Gütersloh Hbf",
    "Haffkrug",
    "Hagen Hbf",
    "Halle (Saale) Hbf",
    "Hamburg Altona",
    "Hamburg Bergedorf",
    "Hamburg Dammtor",
    "Hamburg Harburg",
    "Hamburg Hbf",
    "Hammerau",
    "Hamm (Westfalen) Pbf",
    "Hanau Hbf",
    "Hannover Hbf",
    "Hausach",
    "Heide (Holstein)",
    "Heidelberg Hbf",
    "Heiligenstadt",
    "Helmstedt",
    "Heppenheim/Bergstraße",
    "Herford",
    "Herzogenrath",
    "Hildesheim Hbf",
    "Homburg (Saar) Hbf",
    "Horb",
    "Hornberg",
    "Hünfeld",
    "Husum",
    "Ibbenbüren",
    "Immendingen",
    "Immenstadt",
    "Ingolstadt Hbf",
    "Itzehoe",
    "Jena Paradies",
    "Kaiserslautern Hbf",
    "Karlsruhe-Durlach",
    "Karlsruhe Hbf",
    "Kassel-Wilhelmshöhe",
    "Kaufbeuren",
    "Kehl",
    "Keitum",
    "Kempten (Allgäu) Hbf",
    "Kiel Hbf",
    "Klanxbüll",
    "Koblenz Hbf",
    "Köln/Bonn Flughafen",
    "Köln Hbf",
    "Köln Messe/Deutz",
    "Köln Messe/Deutz",
    "Kölpinsee",
    "Konstanz",
    "Koserow",
    "Köthen",
    "Kreiensen",
    "Kufstein",
    "Landstuhl",
    "Langenhagen Mitte",
    "Langenhagen Pferde",
    "Leer/Ostfriesl",
    "Leinefelde",
    "Leipzig/Halle Flughafen",
    "Leipzig Hbf",
    "Lichtenfels",
    "Limburg Süd",
    "Lindau Hbf",
    "Lingen (Ems)",
    "Lippstadt",
    "Lübbenau Spreew",
    "Lübben (Spreew)",
    "Lübeck Hbf",
    "Ludwigsburg",
    "Ludwigshafen (Rhein) Hbf",
    "Ludwigslust",
    "Lüneburg",
    "Lutherstadt Eisleben",
    "Lutherstadt Wittenberg",
    "Magdeburg-Buckau",
    "Magdeburg Hbf",
    "Mainz Hbf",
    "Mannheim Hbf",
    "Marburg (Lahn)",
    "Marienhafe",
    "Meckenbeuren",
    "Memmingen",
    "Meppen",
    "Metzingen (Württemberg)",
    "Minden (Westfalen)",
    "Mittenwald",
    "Mönchengladbach Hbf",
    "Montabaur",
    "Morsum (Sylt)",
    "Mühlacker",
    "Mülheim Hbf",
    "München Hbf",
    "München Ost Pbf",
    "München-Pasing",
    "Munster (Örtze)",
    "Münster (Westfalen) Pbf",
    "Naumburg (Saale) Hbf",
    "Neumünster",
    "Neuss Westseite",
    "Neustadt (Kr Mbg)",
    "Neustadt (Weinstraße) Hbf",
    "Neust/Aisch Bf",
    "Neustrelitz Hbf",
    "Neu-Ulm",
    "Niebüll",
    "Nienburg (Weser)",
    "Norddeich",
    "Norddeich Mole",
    "Norden",
    "Nordhausen",
    "Northeim (bei Hannover)",
    "Nürnberg Hbf",
    "Nürtingen",
    "Oberau",
    "Oberhausen Hbf",
    "Oberstdorf",
    "Offenbach (Main) Hbf",
    "Offenburg",
    "Oldenburg (Holstein)",
    "Oldenburg (Oldb) Hbf",
    "Osnabrück Hbf",
    "Ostseebad Binz",
    "Paderborn Hbf",
    "Papenburg (Ems)",
    "Pasewalk",
    "Passau Hbf",
    "Peine",
    "Pforzheim Hbf",
    "Piding",
    "Plattling",
    "Plochingen",
    "Potsdam Hbf",
    "Prenzlau",
    "Prien a Chiemsee",
    "Puttgarden",
    "Radolfzell",
    "Rastatt",
    "Ravensburg",
    "Recklinghausen Hbf",
    "Regensburg Hbf",
    "Remagen",
    "Rendsburg",
    "Reutlingen Hbf",
    "Rheine",
    "Rheydt Pbf",
    "Ribnitz-Damgarten West",
    "Riesa",
    "Rosenheim",
    "Rostock Hbf",
    "Rottweil",
    "Saalfeld (Saale)",
    "Saarbrücken Hbf",
    "Salzburg Hbf",
    "Salzwedel",
    "Sangerhausen",
    "Schaffhausen PB",
    "Scharbeutz",
    "Schleswig",
    "Schlüchtern",
    "Schmollensee",
    "Schönebeck(Elbe)",
    "Schorndorf",
    "Schwäbisch Gmünd",
    "Schwerin Hbf",
    "Seebad Heringsdf",
    "Siegburg/Bonn",
    "Sierksdorf",
    "Singen (Htw)",
    "Soest",
    "Solingen Hbf",
    "Sonthofen",
    "Stadtallendorf",
    "Steinach/R o d T",
    "Stendal",
    "St. Georgen/Schwarzwald",
    "Stralsund",
    "Straubing",
    "Stubbenfelde",
    "Stuttgart Hbf",
    "Tantow",
    "Timmendorfer Strand",
    "Trassenheide",
    "Traunstein",
    "Treuchtlingen",
    "Treysa",
    "Triberg",
    "Trier Hbf",
    "Tübingen Hbf",
    "Tuttlingen",
    "Tutzing",
    "Übersee",
    "Ückeritz",
    "Uelzen",
    "Ulm Hbf",
    "Unterlüß",
    "Vaihingen (Enz)",
    "Velgast",
    "Verden (Aller)",
    "Villingen (Schwarzwald)",
    "Wabern (Bz Kassel)",
    "Wanne-Eickel Hbf",
    "Warburg (Westfalen)",
    "Waren (Müritz)",
    "Warnemünde",
    "Weimar",
    "Weinheim (Bergstraße)",
    "Weißenfels",
    "Westerland (Sylt)",
    "Westerstede-Ocholt",
    "Wiesbaden Hbf",
    "Wiesloch-Walldorf",
    "Wittenberge",
    "Wittlich Hbf",
    "Wolfsburg Hbf",
    "Wolgast",
    "Wolgaster Fähre",
    "Wolgast Hafen",
    "Worms Hbf",
    "Wuppertal Hbf",
    "Würzburg Hbf",
    "Zempin",
    "Zinnowitz",
    "Züssow",
]
